import type { Product } from '../../types/product'
import { subDays, subHours } from 'date-fns'

const now = new Date()

export const data: Product[] = [
  {
    id: '5ece2c077e39da27658aa8a9',
    attributes: ['Healthcare'],
    category: 'constant',
    createdAt: subDays(now, 1).getTime(),
    currency: '$',
    image: '/assets/products/product-1.jpeg',
    inStock: true,
    isAvailable: true,
    isShippable: false,
    name: 'おにぎり・塩',
    price: 220,
    quantity: 85,
    sku: '401_1BBXBK',
    status: 'published',
    updatedAt: subHours(now, 6).getTime(),
    variants: 2,
  },
  {
    id: '5ece2c0d16f70bff2cf86cd8',
    attributes: ['Makeup'],
    category: 'change',
    createdAt: subDays(now, 3).getTime(),
    currency: '$',
    image: '/assets/products/product-2.jpeg',
    inStock: false,
    isAvailable: false,
    isShippable: true,
    name: 'おにぎり・銀鮭',
    price: 240,
    quantity: 60,
    sku: '978_UBFGJC',
    status: 'published',
    updatedAt: subDays(subHours(now, 8), 2).getTime(),
    variants: 1,
  },
  {
    id: '5ece2c123fad30cbbff8d060',
    attributes: ['Variety of styles'],
    category: 'constant',
    createdAt: subDays(now, 6).getTime(),
    currency: '$',
    image: '/assets/products/product-3.jpeg',
    inStock: true,
    isAvailable: true,
    isShippable: false,
    name: '唐揚げ・塩',
    price: 400,
    quantity: 30,
    sku: '211_QFEXJO',
    status: 'draft',
    updatedAt: subDays(subHours(now, 2), 1).getTime(),
    variants: 5,
  },
  {
    id: '5ece2c1be7996d1549d94e34',
    attributes: ['Skincare'],
    category: 'change',
    createdAt: subDays(now, 12).getTime(),
    currency: '$',
    image: '/assets/products/product-4.jpeg',
    inStock: true,
    isAvailable: false,
    isShippable: true,
    name: '唐揚げ・甘ダレ',
    price: 400,
    quantity: 35,
    sku: '321_UWEAJT',
    status: 'published',
    updatedAt: subDays(subHours(now, 7), 1).getTime(),
    variants: 1,
  },
]
