import { subDays, subHours } from 'date-fns'
import type { Order } from '../../types/order'

const now = new Date()

export const orders: Order[] = [
  {
    id: '5ecb8a6d9f53bfae09e16115',
    createdAt: subDays(subHours(now, 4), 1).getTime(),
    currency: '$',
    company: 'アイリスオーヤマ',
    customer: {
      address1: 'Street John Wick, no. 7',
      address2: 'House #25',
      city: 'San Diego',
      country: 'USA',
      email: 'miron.vitold@devias.io',
      name: '山田 健太郎',
    },
    items: [
      {
        id: '5ecb8abbdd6dfb1f9d6bf98b',
        billingCycle: 'monthly',
        currency: '$',
        name: 'Project Points',
        quantity: 25,
        unitAmount: 50.25,
      },
      {
        id: '5ecb8ac10f116d04bed990eb',
        billingCycle: 'monthly',
        currency: '$',
        name: 'Freelancer Subscription',
        quantity: 1,
        unitAmount: 5.0,
      },
    ],
    number: '友田 晃司',
    paymentMethod: 'CreditCard',
    status: 'pending',
    totalAmount: 500.0,
  },
  {
    id: '5ecb8a738aa6f3e577c2b3ec',
    createdAt: subDays(subHours(now, 7), 1).getTime(),
    currency: '$',
    company: 'トヨタ自動車東日本',
    customer: {
      address1: 'Street John Wick, no. 7',
      address2: 'House #25',
      city: 'San Diego',
      country: 'USA',
      email: 'miron.vitold@devias.io',
      name: '田中 陽子',
    },
    items: [
      {
        id: '5ecb8abbdd6dfb1f9d6bf98b',
        billingCycle: 'monthly',
        currency: '$',
        name: 'Project Points',
        quantity: 25,
        unitAmount: 50.25,
      },
      {
        id: '5ecb8ac10f116d04bed990eb',
        billingCycle: 'monthly',
        currency: '$',
        name: 'Freelancer Subscription',
        quantity: 1,
        unitAmount: 5.0,
      },
    ],
    number: 'DEV-101',
    paymentMethod: 'PayPal',
    status: 'complete',
    totalAmount: 1200,
  },
  {
    id: '5ecb8a795e53f134013eba3b',
    createdAt: subDays(subHours(now, 2), 2).getTime(),
    currency: '$',
    company: '東京エレクトロン宮城',
    customer: {
      address1: 'Street John Wick, no. 7',
      address2: 'House #25',
      city: 'San Diego',
      country: 'USA',
      email: 'miron.vitold@devias.io',
      name: '佐藤 美香子',
    },
    items: [
      {
        id: '5ecb8abbdd6dfb1f9d6bf98b',
        billingCycle: 'monthly',
        currency: '$',
        name: 'Project Points',
        quantity: 25,
        unitAmount: 50.25,
      },
      {
        id: '5ecb8ac10f116d04bed990eb',
        billingCycle: 'monthly',
        currency: '$',
        name: 'Freelancer Subscription',
        quantity: 1,
        unitAmount: 5.0,
      },
    ],
    number: 'DEV-100',
    paymentMethod: 'CreditCard',
    status: 'canceled',
    totalAmount: 800,
  },
  {
    id: '5ecb8a7f738cc572a9ce0277',
    createdAt: subDays(subHours(now, 3), 5).getTime(),
    currency: '$',
    company: 'バイタルネット',
    customer: {
      address1: 'Street John Wick, no. 7',
      address2: 'House #25',
      city: 'San Diego',
      country: 'USA',
      email: 'miron.vitold@devias.io',
      name: '鈴木 太一',
    },
    items: [
      {
        id: '5ecb8abbdd6dfb1f9d6bf98b',
        billingCycle: 'monthly',
        currency: '$',
        name: 'Project Points',
        quantity: 25,
        unitAmount: 50.25,
      },
      {
        id: '5ecb8ac10f116d04bed990eb',
        billingCycle: 'monthly',
        currency: '$',
        name: 'Freelancer Subscription',
        quantity: 1,
        unitAmount: 5.0,
      },
    ],
    number: 'DEV-99',
    paymentMethod: 'PayPal',
    status: 'rejected',
    totalAmount: 700,
  },
  {
    id: '5e86805e2bafd54f66cc95c3',
    createdAt: subDays(subHours(now, 1), 6).getTime(),
    currency: '$',
    company: 'キタセキ',
    customer: {
      address1: 'Street John Wick, no. 7',
      address2: 'House #25',
      city: 'San Diego',
      country: 'USA',
      email: 'miron.vitold@devias.io',
      name: '高橋 さやか',
    },
    items: [
      {
        id: '5ecb8abbdd6dfb1f9d6bf98b',
        billingCycle: 'monthly',
        currency: '$',
        name: 'Project Points',
        quantity: 25,
        unitAmount: 50.25,
      },
      {
        id: '5ecb8ac10f116d04bed990eb',
        billingCycle: 'monthly',
        currency: '$',
        name: 'Freelancer Subscription',
        quantity: 1,
        unitAmount: 5.0,
      },
    ],
    number: 'DEV-98',
    paymentMethod: 'PayPal',
    status: 'complete',
    totalAmount: 600,
  },
  {
    id: '5ecb8a85a850c16fa413849c',
    createdAt: subDays(subHours(now, 3), 7).getTime(),
    currency: '$',
    company: 'アイリスオーヤマ',
    customer: {
      address1: 'Street John Wick, no. 7',
      address2: 'House #25',
      city: 'San Diego',
      country: 'USA',
      email: 'miron.vitold@devias.io',
      name: '伊藤 裕太',
    },
    items: [
      {
        id: '5ecb8abbdd6dfb1f9d6bf98b',
        billingCycle: 'monthly',
        currency: '$',
        name: 'Project Points',
        quantity: 25,
        unitAmount: 50.25,
      },
      {
        id: '5ecb8ac10f116d04bed990eb',
        billingCycle: 'monthly',
        currency: '$',
        name: 'Freelancer Subscription',
        quantity: 1,
        unitAmount: 5.0,
      },
    ],
    status: 'pending',
    number: 'DEV-97',
    paymentMethod: 'CreditCard',
    totalAmount: 1200,
  },
  {
    id: '5ecb8a8e69ba2e409ea0168f',
    createdAt: subDays(subHours(now, 6), 8).getTime(),
    currency: '$',
    company: 'キタセキ',
    customer: {
      address1: 'Street John Wick, no. 7',
      address2: 'House #25',
      city: 'San Diego',
      country: 'USA',
      email: 'miron.vitold@devias.io',
      name: '渡辺 由美子',
    },
    items: [
      {
        id: '5ecb8abbdd6dfb1f9d6bf98b',
        billingCycle: 'monthly',
        currency: '$',
        name: 'Project Points',
        quantity: 25,
        unitAmount: 50.25,
      },
      {
        id: '5ecb8ac10f116d04bed990eb',
        billingCycle: 'monthly',
        currency: '$',
        name: 'Freelancer Subscription',
        quantity: 1,
        unitAmount: 5.0,
      },
    ],
    number: 'DEV-96',
    paymentMethod: 'CreditCard',
    status: 'complete',
    totalAmount: 1000,
  },
  {
    id: '5ecb8a9341c68839d387e1c4',
    createdAt: subDays(subHours(now, 7), 8).getTime(),
    currency: '$',
    company: 'アイリスオーヤマ',
    customer: {
      address1: 'Street John Wick, no. 7',
      address2: 'House #25',
      city: 'San Diego',
      country: 'USA',
      email: 'miron.vitold@devias.io',
      name: '中村 光男',
    },
    items: [
      {
        id: '5ecb8abbdd6dfb1f9d6bf98b',
        billingCycle: 'monthly',
        currency: '$',
        name: 'Project Points',
        quantity: 25,
        unitAmount: 50.25,
      },
      {
        id: '5ecb8ac10f116d04bed990eb',
        billingCycle: 'monthly',
        currency: '$',
        name: 'Freelancer Subscription',
        quantity: 1,
        unitAmount: 5.0,
      },
    ],
    number: 'DEV-95',
    paymentMethod: 'PayPal',
    status: 'rejected',
    totalAmount: 800,
  },
  {
    id: '5ecb8a984bfbb97c9ae458e8',
    createdAt: subDays(subHours(now, 6), 9).getTime(),
    currency: '$',
    company: 'キタセキ',
    customer: {
      address1: 'Street John Wick, no. 7',
      address2: 'House #25',
      city: 'San Diego',
      country: 'USA',
      email: 'miron.vitold@devias.io',
      name: '高橋 さやか',
    },
    items: [
      {
        id: '5ecb8abbdd6dfb1f9d6bf98b',
        billingCycle: 'monthly',
        currency: '$',
        name: 'Project Points',
        quantity: 25,
        unitAmount: 50.25,
      },
      {
        id: '5ecb8ac10f116d04bed990eb',
        billingCycle: 'monthly',
        currency: '$',
        name: 'Freelancer Subscription',
        quantity: 1,
        unitAmount: 5.0,
      },
    ],
    number: 'DEV-94',
    paymentMethod: 'CreditCard',
    status: 'canceled',
    totalAmount: 1200,
  },
  {
    id: '5ecb8aa08d9127dba654ce7a',
    createdAt: subDays(subHours(now, 3), 10).getTime(),
    currency: '$',
    company: 'トヨタ自動車東日本',
    customer: {
      address1: 'Street John Wick, no. 7',
      address2: 'House #25',
      city: 'San Diego',
      country: 'USA',
      email: 'miron.vitold@devias.io',
      name: '小林 あかり',
    },
    items: [
      {
        id: '5ecb8abbdd6dfb1f9d6bf98b',
        billingCycle: 'monthly',
        currency: '$',
        name: 'Project Points',
        quantity: 25,
        unitAmount: 200,
      },
      {
        id: '5ecb8ac10f116d04bed990eb',
        billingCycle: 'monthly',
        currency: '$',
        name: 'Freelancer Subscription',
        quantity: 1,
        unitAmount: 220,
      },
    ],
    number: 'DEV-93',
    paymentMethod: 'PayPal',
    status: 'canceled',
    totalAmount: 440,
  },
]

export const order: Order = {
  id: '5ecb8a6879877087d4aa2690',
  coupon: null,
  createdAt: subDays(subHours(now, 4), 1).getTime(),
  currency: '$',
  company: 'バイタルネット',
  customer: {
    address1: 'Street John Wick, no. 7',
    address2: 'House #25',
    city: 'San Diego',
    country: 'USA',
    email: 'miron.vitold@devias.io',
    name: '加藤 拓也',
  },
  items: [
    {
      id: '5ecb8abbdd6dfb1f9d6bf98b',
      billingCycle: 'monthly',
      currency: '$',
      name: 'Project Points',
      quantity: 25,
      unitAmount: 50.25,
    },
    {
      id: '5ecb8ac10f116d04bed990eb',
      billingCycle: 'monthly',
      currency: '$',
      name: 'Freelancer Subscription',
      quantity: 1,
      unitAmount: 5.0,
    },
  ],
  logs: [
    {
      id: '9a50be1fa5ec7317d459d5a8',
      createdAt: subHours(Date.now(), 18).getTime(),
      message: 'Stripe charge complete (Charge ID: 5ecb8a6879877087d4aa2690)',
    },
    {
      id: '41845b427db837502b4d6a57',
      createdAt: subHours(Date.now(), 21).getTime(),
      message: 'Order status changed from Pending payment to Completed.',
    },
  ],
  number: 'DEV-103',
  paymentMethod: 'CreditCard',
  promotionCode: 'PROMO1',
  status: 'pending',
  totalAmount: 500.0,
}
